services:
  db:
    container_name: pgdatabase
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: pgdatabase
      POSTGRES_PASSWORD: pgdatabase
      POSTGRES_DB: ny_taxi
    ports:
      - '5433:5432'
    volumes:
      - vol-pgdata:/var/lib/postgresql/data
    networks:
      - airflow_hw_default

  ## Week 1 - docker pg-admin 
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "pgadmin"
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - vol-pgadmin_data:/var/lib/pgadmin  


volumes:
  vol-pgdata:
    name: vol-pgdata
  
  ## week 1 - pg-admin
  # vol-pgadmin_data:
  #   name: vol-pgadmin_data

## Week 2 - network connection.
networks:
  airflow_hw_default:
    external:
      name: airflow_hw_default